name: CodeCheck

on:
  push:
    branches:
      - main 

jobs:
  check-syntax:
    runs-on: ubuntu-latest

    steps:
    - name: Repository checkout
      uses: actions/checkout@v2
      
    - name: .NET Core setup
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x' 

    - name: Dependencies restore
      run: dotnet restore

    - name: Install StyleCop.GlobalTool
      run: dotnet add package StyleCop.Analyzers --version 1.1.118

    - name: Run StyleCop for style check
      run: dotnet build /p:StyleCopEnabled=true
    

    